from .nbp_gemini_image2 import NODE_CLASS_MAPPINGS as _MAP1, NODE_DISPLAY_NAME_MAPPINGS as _NAMES1
from .nbp_gemini_composite import NODE_CLASS_MAPPINGS as _MAP2, NODE_DISPLAY_NAME_MAPPINGS as _NAMES2

NODE_CLASS_MAPPINGS = {**_MAP1, **_MAP2}
NODE_DISPLAY_NAME_MAPPINGS = {**_NAMES1, **_NAMES2}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
